### ISSUE TITLE
Add a Warning to README about Cheating 

### ISSUE THREAD

**Issue by he3als** [Nilsen84/lunar-client-agents#1]
Due to some of these modifications being cheats (I presume LunarEnable removes the ability of servers blocking mods too), add a warning clearly saying in the README that you are cheating by using LunarHitDelayFix and LunarEnable (at least you are most likely are, as servers disable mods for a reason, most likely due to it being against the rules). As people will mainly use LunarEnable for Hypixel too, also say that it is cheating on Hypixel.

Also, to make sure that there is no confusion if LunarHitDelayFix is simply a bug fix or a cheat, maybe change the name of the mod/agent? Instead of LunarHitDelayFix, maybe change it to something like LunarNoHitDelay. It is your choice, just an idea.

**Comment by Nilsen84** [comment]
done
