### ISSUE TITLE
How can I compile a jar file for lunar

### ISSUE THREAD

**Issue by ACloseOne** [Nilsen84/lunar-client-agents#11]

**Comment by Scherso** [comment]
@ACloseOne 

If you’re interested in building a `.jar` file from a repository, you would need to install git, or download the source tree of an agent, then build normally with either `gradlew.bat` for Windows, or `gradlew` for Un*x.

**Comment by Nilsen84** [comment]
> @ACloseOne
> 
> If you’re interested in building a `.jar` file from a repository, you would need to install git, or download the source tree of an agent, then build normally with either `gradlew.bat` for Windows, or `gradlew` for Un*x.

Run this in the root directory of the repository:
`$ ./gradlew build`
It will generate a `build` directory containing all the agent jars.
