### ISSUE TITLE
Just wondering if the HitDelayFix agent removes the 12 cps cap that is in lunar client.

### ISSUE THREAD

**Issue by Crazymanverycrazy** [Nilsen84/lunar-client-agents#13]
Also why are so many people trying to inject cheats into lunar client qt?

**Comment by Scherso** [comment]
@Crazymanverycrazy 

The only returned value in HitDelayFix is 0, modifying an integer of `leftClickCounter` in Minecraft to return 0 when it is 10. So no, the agent doesn’t remove this “12 cps cap that is in lunar client.”

> `                    ClassWriter cw = new ClassWriter(cr, 0);`
> `return cw.toByteArray();`

**Comment by Nilsen84** [comment]
> @Crazymanverycrazy
> 
> The only returned value in HitDelayFix is 0, modifying an integer of `leftClickCounter` in Minecraft to return 0 when it is 10. So no, the agent doesn’t remove this “12 cps cap that is in lunar client.”
> 
> > `                    ClassWriter cw = new ClassWriter(cr, 0);`
> > `return cw.toByteArray();`

This, also, the 12 cps cap is a myth.
