### ISSUE TITLE
Cracked account agent not working with latest lunar update.

### ISSUE THREAD

**Issue by Dozairu** [Nilsen84/lunar-client-agents#21]
I am using Lunar QT compiled from github (cloned and compiled today)
I am using Arch Linux as my OS

Lunar has updated their client which made Microsoft account a requirement, they have completely removed mojang login support.
I would assume because of these changes, it has broken cracked account login.

**Comment by yBxlzz** [comment]
> I am using Lunar QT compiled from github (cloned and compiled today) I am using Arch Linux as my OS
> 
> Lunar has updated their client which made Microsoft account a requirement, they have completely removed mojang login support. I would assume because of these changes, it has broken cracked account login.

HI... the same thing happen to me what i did was just downloaded it from the latest agents and it worked...
you can download the crackedaccount from here and it should work https://github.com/Nilsen84/lunar-client-agents/releases/tag/v1.2.0

**Comment by meow-plus** [comment]
Hi, I use Cracked Account today with Lunar Client Qt (Version 1.3.0) it works fine, Do you add it to Agent list with username Option?
I am using Ubuntu 21.10

**Comment by Dozairu** [comment]
This issue was created before the agents were updated which solved this issue. I forgot to close it

cheers guys
