### ISSUE TITLE
cracked account doesnt work for some reason???

### ISSUE THREAD

**Issue by SolarisAVR** [Nilsen84/lunar-client-agents#6]
![image](https://user-images.githubusercontent.com/95339771/161877827-0e9862ca-8885-4edb-b3ed-8064e9619462.png)
![image](https://user-images.githubusercontent.com/95339771/161877861-f879156b-39e2-4c62-962c-7c8ad610eefa.png)

**Comment by Nilsen84** [comment]
It only works if you don't have any real accounts added.
